### ISSUE TITLE
Need to add a profile

### ISSUE THREAD

**Issue by wlv84** [wlv84/new_repo_fk#1]

**Comment by trong89** [comment]
@wlv84 I'd like to fix #1.

**Comment by wlv84** [comment]
@trong89 Thx, I'll assign #1 to you. Please fix #1 by the task list below:
- [ ] Update README to target #1.
- [ ] Add PROFILE with proper description.
- [ ] Issue a pull request for review.

**Comment by trong89** [comment]
@wlv84 Pull request has been opened for #1, plz review.

**Comment by wlv84** [comment]
@trong89 Thx for the hard work, the PR has been merged 👍!!!
